openapi: 3.0.0
info:
  title: Purple Ops API
  version: '1.0'
servers:
  - url: https://api.purple-ops.io
paths:
  /v1:
    post:
      summary: Search PurpleOps ransomware API.
      operationId: purpleOpsApiCall
      tags:
        - Actions
      requestBody:
        required: true
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              properties:
                auth_token:
                  type: string
                  description: Authentication token for API access.
                action:
                  type: string
                  description: Action to be performed -> getDemo, getLast, getGroup.
                groupName:
                  type: string
                  description: Required if action = getGroup. Threat group to search for.
                keyword:
                  type: string
                  description: Required if action = getKeyword. Keyword can be a company, etc.
              required:
                - auth_token
                - action
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      type: object
                      properties:
                        Victim_Name:
                          type: string
                        Additional_Info:
                          type: string
                        Dates:
                          type: string
                          format: date-time
                        Group_Name:
                          type: string
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    description: The requested action could not be found.
