openapi: 3.0.0
info:
  title: Purple Ops API
  version: "1.0"
servers:
  - url: https://api.purple-ops.io/v1
paths:
  /:
    post:
      summary: Perform an action with optional keyword
      operationId: performAction
      tags:
        - Purple Ops
      requestBody:
        required: true
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              properties:
                action:
                  type: string
                  enum: [getDemo, getLast, getGroup, getKeyword]
                keyword:
                  type: string
              required:
                - action
      responses:
        '200':
          description: Successful operation
          content:
            text/plain:
              schema:
                type: string
      security:
        - ApiKeyAuth: []
components:
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: x-test-api-key
