openapi: 3.0.0

info:
  title: Purple Ops API
  description: Interact with the Purple Ops API for various operations.
  version: "1.0.0"

servers:
  - url: https://api.purple-ops.io/v1

paths:
  /:
    post:
      summary: Perform an action with the Purple Ops API
      operationId: performAction
      tags:
        - Purple Ops
      requestBody:
        required: true
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              properties:
                auth_token:
                  type: string
                  description: "Authentication token for API access."
                  example: ""
                action:
                  type: string
                  example: "getLast"
                  description: "Action to perform. Options are 'getDemo', 'getLast', 'getGroup', 'getKeyword'."
                keyword:
                  type: string
                  example: "exampleKeyword"
                  description: "Optional keyword for the 'getKeyword' action."
              required:
                - auth_token
                - action
responses:
  '200':
    description: OK
    content:
      application/json:
        schema:
          type: object
          properties:
            success:
              type: boolean
            data:
              type: string
