openapi: 3.0.0
info:
  title: Purple Ops API
  version: '1.0'
servers:
  - url: https://api.purple-ops.io/v1
paths:
  /:
    post:
      summary: Execute an action call
      operationId: executeAction
      tags:
        - Actions
      requestBody:
        required: true
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              properties:
                auth_token:
                  type: string
                  description: Authentication token for API access.
                action:
                  type: string
                  description: Action to be performed.
                  enum: [getDemo, getLast, getGroup, getKeyword]
                keyword:
                  type: string
                  description: Optional keyword for custom search. Required if action is `getKeyword`.
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      type: object
                      properties:
                        Victim_Name:
                          type: string
                        Additional_Info:
                          type: string
                        Dates:
                          type: string
                          format: date-time
                        Group_Name:
                          type: string
